/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Accounts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AdminPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "McpToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OAuth": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Server": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
  }
}

import "sst"
export {}