/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Accounts": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Audit": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Auth": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "Calendars": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "EncryptionKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OAuth": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PreSignUp": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Server": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Web": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}

import "sst"
export {}